const DATA = [
  [
    [ "春眠不觉晓", "chun mian bu jue xiao" ],
    [ "处处闻啼鸟", "chu chu wen ti niao" ],
    [ "夜来风雨声", "ye lai feng yu sheng" ],
    [ "花落知多少", "hua luo zhi duo shao" ] ,
  ],
  [
    [ "爆竹声中一岁除", "bao zhu sheng zhong yi sui chu" ],
    [ "春风送暖入屠苏", "chun feng song nuan ru tu su" ],
    [ "千门万户曈曈日", "qian men wan hu tong tong ri" ],
    [ "总把新桃换旧符", "zong ba xin tao huan jiu fu" ],
  ],
  [
    [ "云对雨，雪对风，晚照对晴空。", "yun dui yu xue dui feng wan zhao dui qing kong" ],
    [ "来鸿对去雁，宿鸟对鸣虫。", "lai hong dui qu yan su niao dui ming chong" ],
    [ "三尺剑，六钧弓。岭北对江东。", "san chi jian liu jun gong ling bei dui jiang dong" ],
    [ "人间清暑殿，天上广寒宫。", "ren jian qing shu dian tian shang guang han gong"],
    [ "两岸晓烟杨柳绿，一园春雨杏花红。", "liang an xiao yan yang liu lv yi yuan chun yu xing hua hong" ],
    [ "两鬓风霜，途次早行之客", "liang bin feng shuang tu ci zao xing zhi ke" ],
    [ "一蓑烟雨，溪边晚钓之翁。", "yi suo yan yu xi bian wan diao zhi weng" ],
    [ "沿对革，异对同。白叟对黄童。", "yan dui ge yi dui tong bai sou dui huang tong" ],
    [ "江风对海雾，牧子对渔翁。", "jiang feng dui hai wu mu zi dui yu weng"],
    [ "颜巷陋，阮途穷。冀北对辽东。", "yan xiang lou ruan tu qiong ji bei dui liao dong"],
    [ "池中濯足水，门外打头风。", "chi zhong zhuo zu shui men wai da tou feng"],
    [ "梁帝讲经同泰寺，汉皇置酒未央宫。", "liang di jiang jing tong tai si han huang zhi jiu wei yang gong"],
    [ "尘虑萦心，懒抚七弦绿绮；", "chen lv yin xin lan fu qi xian lv qi" ],
    [ "霜华满鬓，羞看百炼青铜。", "shuang hua man bin xiu kan bai lian qing tong" ],
    [ "贫对富，塞对通。野叟对溪童。", "pin dui fu se dui tong ye sou dui xi tong" ],
    [ "鬓皤对眉绿，齿皓对唇红。", "bin po dui mei lv chi hao dui chun hong" ],
    [ "天浩浩，日融融。佩剑对弯弓。", "tian hao hao ri rong rong pei jian dui wan gong"],
    [ "半溪流水绿，千树落花红。", "ban xi liu shui lv qian shu luo hua hong"],
    [ "野渡燕穿杨柳雨，芳池鱼戏芰荷风。", "ye du yan chuan yang liu yu fang chi yu xi ji he feng"],
    [ "女子眉纤，额下现一弯新月；", "nv zi mei xian e xia xian yi wan xin yue" ],
    [ "男儿气壮，胸中吐万丈长虹。", "nan er qi zhuang xiong zhong tu wan zhang chang hong"]
  ],
  [
    [ "春对夏，秋对冬。暮鼓对晨钟。", "chun dui xia qiu dui dong mu gu dui chen zhong" ],
    [ "观山对玩水，绿竹对苍松。", "guan shan dui wan shui lv zhu dui cang song" ],
    [ "冯妇虎，叶公龙。舞蝶对鸣蛩。", "feng fu hu ye gong long wu die dui ming qiong" ],
    [ "衔泥双紫燕，课蜜几黄蜂。", "xian ni shuang zi yan ke mi ji huang feng" ],
    [ "春日园中莺恰恰，秋天寒外雁雍雍。", "chun ri yuan zhong ying qia qia qiu tian sai wai yan yong yong" ],
    [ "秦岭云横，迢递八千远路；", "qin ling yun heng tiao di ba qian yuan lu" ],
    [ "巫山雨洗，嵯峨十二危峰。", "wu shan yu xi cuo e shi er wei feng" ],
    [ "明对暗，淡对浓。上智对中庸。", "ming dui an dan dui nong shang zhi dui zhong yong" ],
    [ "镜奁对衣笥，野杵对村舂。", "jing lian dui yi si ye chu dui cun chong" ],
    [ "花灼烁，草蒙茸。九夏对三冬。", "hua zhuo shuo cao meng rong jiu xia dui san dong" ],
    [ "台高名戏马，斋小号蟠龙。", "tai gao ming xi ma zhai xiao hao pan long" ],
    [ "手擘蟹螯从毕卓，身披鹤氅自王恭。", "shou bo xie ao cong bi zhuo shen pi he chang zi wang gong" ],
    [ "五老峰高，秀插云霄如玉笔；", "wu lao feng gao xiu cha yun xiao ru yu bi" ],
    [ "三姑石大，响传风雨若金镛。", "san gu shi da xiang chuan feng yu ruo jin yong" ],
    [ "仁对义，让对恭。禹舜对羲农。", "ren dui yi rang dui gong yu shun dui xi nong" ],
    [ "雪花对云叶，芍药对芙蓉。", "xue hua dui yun ye shao yao dui fu rong" ],
    [ "陈后主，汉中宗。绣虎对雕龙。", "chen hou zhu han zhong zong xiu hu dui diao long" ],
    [ "柳塘风淡淡，花圃月浓浓。", "liu tang feng dan dan hua pu yue nong nong" ],
    [ "春日正宜朝看蝶，秋风那更夜闻蛩。", "chun ri zheng yi zhao kan die qiu feng na geng ye wen qiong" ],
    [ "战士邀功，必借干戈成勇武；", "zhan shi yao gong bi jie gan ge cheng yong wu" ],
    [ "逸民适志，须凭诗酒养疏慵。", "yi min shi zhi xiang chuan feng yu ruo jin yong" ],
  ],
  [
    [ "楼对阁，户对窗。巨海对长江。", "lou dui ge hu dui chuang ju hai dui chang jiang" ],
    [ "蓉裳对蕙帐，玉斝对银釭。", "rong chang dui hui zhang yu jia dui yin gang" ],
    [ "青布幔，碧油幢。宝剑对金缸。", "qing bu man bi you zhuang bao jian dui jin gang" ],
    [ "忠心安社稷，利口覆家邦。", "zhong xin an she ji li kou fu jia bang" ],
    [ "世祖中兴延马武，桀王失道杀龙逄。", "shi zu zhong xing yan ma wu jie wang shi dao sha long tang" ],
    [ "秋雨潇潇，漫烂黄花都满径；", "qiu yu xiao xiao man lan huang hua dou man jing" ],
    [ "春风袅袅，扶疏绿竹正盈窗。", "chun feng niao niao fu shu lv zhu zheng ying chuang" ],
    [ "旌对旆，盖对幢。故国对他邦。", "jing dui pei gai dui zhuang gu guo dui ta bang" ],
    [ "千山对万水，九泽对三江。", "qian shan dui wan shui jiu ze dui san jiang" ],
    [ "山岌岌，水淙淙。鼓振对钟撞。", "shan ji ji shui cong cong gu zhen dui zhong zhuang" ],
    [ "清风生酒舍，皓月照书窗。", "qing feng sheng jiu she hao yue zhao shu chuang" ],
    [ "阵上倒戈辛纣战，道旁系剑子婴降。", "zhen shang dao ge xin zhou zhan dao pang ji jian zi ying xiang" ],
    [ "夏日池塘，出没浴波鸥对对；", "xia ri chi tang chu mo yu bo ou dui dui" ],
    [ "春风帘幕，往来营垒燕双双。", "chun feng lian mu wang lai ying lei yan shuanug shuang" ],
    [ "铢对两，只对双。华岳对湘江。", "zhu dui liang zhi dui shuang hua yue dui xiang jiang" ],
    [ "朝车对禁鼓，宿火对寒缸。", "chao che dui jin gu su huo dui han gang" ],
    [ "青琐闼，碧纱窗。汉社对周邦。", "qing suo ta bi sha chuang han she dui zhou bang" ],
    [ "笙箫鸣细细，钟鼓响摐摐。", "sheng xiao ming xi xi zhong gu xiang chuang chuang" ],
    [ "主簿栖鸾名有览，治中展骥姓惟庞。", "zhu bu qi luan ming you lan zhi zhong zhan ji xing wei pang" ],
    [ "苏武牧羊，雪屡餐于北海；", "su wu mu yang xue lv can yu bei hai" ],
    [ "庄周活鲋，水必决于西江。", "zhuang zhou huo fu shui bi jue yu xi jiang" ],
  ],
  [
    [ "茶对酒，赋对诗。燕子对莺儿。", "cha dui jiu fu dui shi yan zi dui ying er" ],
    [ "栽花对种竹，落絮对游丝。", "zai hua dui zhong zhu luo xu dui you si" ],
    [ "四目颉，一足夔。鸲鹆对鹭鸶。", "si mu jie yi zu kui qu yu dui lu si" ],
    [ "半池红菡萏，一架白荼縻。", "ban chi hong han dan yi jia bai tu mi" ],
    [ "几阵秋风能应候，一犁春雨甚知时。", "ji zhen qiu feng neng ying hou yi li chun yu shen zhi shi" ],
    [ "智伯恩深，国士吞变形之炭；", "zhi bo en shen guo shi tun bian xing zhi tan" ],
    [ "羊公德大，邑人竖堕泪之碑。", "yang gong de da yi ren shu duo lei zhi bei" ],
    [ "行对止，速对迟。舞剑对围棋。", "xing dui zhi su dui chi wu jian dui wei qi" ],
    [ "花笺对草字，竹简对毛锥。", "hua jian dui cao zi zhu jian dui mao zhui" ],
    [ "汾水鼎，岘山碑。虎豹对熊罴。", "fen shui ding xian shan bei hu bao dui xiong pi" ],
    [ "花开红锦绣，水漾碧琉璃。", "hua kai hong jin xiu shui yang bi liu li" ],
    [ "去妇因探邻舍枣，出妻为种后园葵。", "qu fu yin tan ling she zao chu qi wei zhong hou yuan kui" ],
    [ "笛韵和谐，仙管恰从云里降；", "di yun he xie xian guan qia cong yun li jiang" ],
    [ "橹声咿轧，渔舟正向雪中移。", "lu sheng yi ya yu zhou zheng xiang xue zhong yi" ],
    [ "戈对甲，鼓对旗。紫燕对黄鹂。", "ge dui jia gu dui qi zi yan dui huang li" ],
    [ "梅酸对李苦，青眼对白眉。", "mei suan dui li ku qing yan dui bai mei" ],
    [ "三弄笛，一围棋。雨打对风吹。", "san nong di yi wei qi yu da dui feng chui" ],
    [ "海棠春睡早，杨柳昼眠迟。", "hai tang chun shui zao yang liu zhou mian chi" ],
    [ "张骏曾为槐树赋，杜陵不作海棠诗。", "zhang jun ceng wei huai shu fu du ling bu zuo hai tang shi" ],
    [ "晋士特奇，可比一斑之豹；", "jin shi te qi ke bi yi ban zhi bao" ],
    [ "唐儒博识，堪为五总之龟。", "tang ru bo shi kan wei wu zong zhi gui" ],
  ],
  [
    [ "来对往，密对稀。燕舞对莺飞。", "lai dui wang mi dui xi yan wu dui ying fei" ],
    [ "风清对月朗，露重对烟微。", "feng qing dui yue lang lu zhong dui yan wei" ],
    [ "霜菊瘦，雨梅肥。客路对渔矶。", "shuang ju shou yu mei fei ke lu dui yu ji" ],
    [ "晚霞舒锦绣，朝露缀珠玑。", "wan xia shu jin xiu zhao lu zhui zhu ji" ],
    [ "夏暑客思欹石枕，秋寒妇念寄边衣。", "xia shu ke si qi shi zhen qiu han fu nian ji bian yi" ],
    [ "春水才深，青草岸边渔父去；", "chun shui cai shen qing cao an bian yu fu qu" ],
    [ "夕阳半落，绿莎原上牧童归。", "xi yang ban luo lv suo yuan shang mu tong gui" ],
    [ "宽对猛，是对非。服美对乘肥。", "kuan dui meng shi dui fei fu mei dui sheng fei" ],
    [ "珊瑚对玳瑁，锦绣对珠玑。", "shan hu dui dai mao jin xiu dui zhu ji" ],
    [ "桃灼灼，柳依依。绿暗对红稀。", "tao zhuo zhuo liu yi yi lv an dui hong xi" ],
    [ "窗前莺并语，帘外燕双飞。", "chuang qian ying bing yu lian wai yan shuang fei" ],
    [ "汉致太平三尺剑，周臻大定一戎衣。", "han zhi tai ping san chi jian zhou zhen da ding yi rong yi" ],
    [ "吟成赏月之诗，只愁月堕；", "yin cheng shang yue zhi shi zhi chou yue duo" ],
    [ "斟满送春之酒，惟憾春归。", "zhen man song chun zhi jiu wei han chun gui" ],
    [ "声对色，饱对饥。虎节对龙旗。", "sheng dui se bao dui ji hu jie dui long qi" ],
    [ "杨花对桂叶，白简对朱衣。", "yang hua dui gui ye bai jian dui zhu yi" ],
    [ "尨也吠，燕于飞。荡荡对巍巍。", "mang ye fei yan yu fei dang dang dui wei wei" ],
    [ "春暄资日气，秋冷借霜威。", "chun xuan zi ri qi qiu leng jie shuang wei" ],
    [ "出使振威冯奉世，治民异等尹翁归。", "chu shi zhen wei feng feng shi zhi min yi deng yin weng gui" ],
    [ "燕我弟兄，载咏棣棠韡韡；", "yan wo di xiong zai yong di tang wei wei" ],
    [ "命伊将帅，为歌杨柳依依。", "ming yi jiang shuai wei ge yang liu yi yi" ],
  ],
  [
    [ "无对有，实对虚。作赋对观书。", "wu dui you shi dui xu zuo fu dui guan shu" ],
    [ "绿窗对朱户，宝马对香车。", "lv chuang dui zhu hu bao ma dui xiang ju" ],
    [ "伯乐马，浩然驴。弋雁对求鱼。", "bo le ma hao ran lv yi yan dui qiu yu" ],
    [ "分金齐鲍叔，奉璧蔺相如。", "fen jin qi bao shu feng bi lin xiang ru" ],
    [ "掷地金声孙绰赋，回文锦字窦滔书。", "zhi di jin sheng sun chuo fu hui wen jin zi dou tao shu" ],
    [ "未遇殷宗，胥靡困傅岩之筑；", "wei yu yin zong xu mi kun fu yan zhi zhu" ],
    [ "既逢周后，太公舍渭水之渔。", "ji feng zhou hou tai gong she wei shui zhi yu" ],
    [ "终对始，疾对徐。短褐对华裾。", "zhong dui shi ji dui xu duan he dui hua ju" ],
    [ "六朝对三国，天禄对石渠。", "liu chao dui san guo tian lu dui shi qu" ],
    [ "千字策，八行书。有若对相如。", "qian zi ce ba hang shu you ruo dui xiang ru" ],
    [ "花残无戏蝶，藻密有潜鱼。", "hua can wu xi die zao mi you qian yu" ],
    [ "落叶舞风高复下，小荷浮水卷还舒。", "luo ye wu feng gao fu xia xiao he fu shui juan huan shu" ],
    [ "爱见人长，共服宣尼休假盖；", "ai xian ren chang gong fu xuan ni xiu jia gai"],
    [ "恐彰已吝，谁知阮裕竟焚车。", "kong zhang ji lin shei zhih ruan yu jing fen ju" ],
    [ "麟对凤，鳖对鱼。内史对中书。", "lin dui feng bie dui yu nei shi dui zhong shu" ],
    [ "犁锄对耒耜，畎浍对郊墟。", "li chu dui lei zi quan hui dui jiao xu" ],
    [ "犀角带，象牙梳。驷马对安车。", "xi jiao dai xiang ya shu si ma dui an ju" ],
    [ "青衣能报赦，黄耳解传书。", "qing yi neng bao she huang er jie chuan shu" ],
    [ "庭畔有人持短剑，门前无客曳长裾。", "ting pan you ren chi duan jian men qian wu ke ye chang ju" ],
    [ "波浪拍船，骇舟人之水宿；", "bo lang pai chuan hai zhou ren zhi shui su" ],
    [ "峰峦绕舍，乐隐者之山居。", "feng luan rao she yao yin zhe zhi shan ju" ],
  ],
  [
    [ "金对玉，宝对珠。玉兔对金乌。", "jin dui yu bao dui zhu yu tu dui jin wu" ],
    [ "孤舟对短棹，一雁对双凫。", "gu zhou dui duan zhao yi yan dui shuang fu" ],
    [ "横醉眼，捻吟须。李白对杨朱。", "heng zui yan nian yin xu li bai dui yang zhu" ],
    [ "秋霜多过雁，夜月有啼乌。", "qiu shuang duo guo yan ye yue you ti wu" ],
    [ "日暖园林花易赏，雪寒村舍酒难沽。", "ri nuan yuan lin hua yi shang xue han cun she jiu nan gu" ],
    [ "人处岭南，善探巨象口中齿；", "ren chu ling nan shan tan ju xiang kou zhong chi" ],
    [ "客居江右，偶夺骊龙颔下珠。", "ke ju jiang you ou duo li long han xian zhu" ],
    [ "贤对圣，智对愚。傅粉对施朱。", "xian dui sheng zhi dui yu fu fen dui shi zhu" ],
    [ "名缰对利锁，挈榼对提壶。", "ming jiang dui li suo qie ke dui ti hu" ],
    [ "鸠哺子，燕调雏。石帐对郇厨。", "jiu bu zi yan tiao chu shi zhang dui xun chu" ],
    [ "烟轻笼岸柳，风急撼庭梧。", "yan qing long an liu feng ji han ting wu" ],
    [ "鸜眼一方端石砚，龙涎三炷博山垆。", "qu yan yi fang duan shi yan long xian san zhu bo shan lu" ],
    [ "曲沼鱼多，可使渔人结网；", "qu zhao yu duo ke shi yu ren jie wang" ],
    [ "平田兔少，漫劳耕者守株。", "ping tian tu shao man lao geng zhe shou zhu" ], 
    [ "秦对赵，越对吴。钓客对耕夫。", "qin dui zhao yue dui wu diao ke dui geng fu" ],
    [ "箕裘对杖履，杞梓对桑榆。", "ji qiu dui zhang lv qi zi dui sang yu" ],
    [ "天欲晓，日将晡。狡兔对妖狐。", "tian yu xiao ri jiang bu jiao tu dui yao hu" ],
    [ "读书甘刺股，煮粥惜焚须。", "du shu gan ci gu zhu zhou xi fen xu" ],
    [ "韩信武能平四海，左思文足赋三都。", "han xin wu neng ping si hai zuo si wen zu fu san du" ],
    [ "嘉遁幽人，适志竹篱茅舍；", "jia dun you ren shi zhi zhu li mao she" ],
    [ "胜游公子，玩情柳陌花衢。", "sheng you gong zi wan qing liu mo hua qu" ]
  ],
  [
    [ "岩对岫，涧对溪，远岸对危堤。", "yan dui xiu jian dui xi yuan an dui wei di" ],
    [ "鹤长对凫短，水雁对山鸡。", "he chang dui fu duan shui yan dui shan ji" ],
    [ "星拱北，月流西，汉露对汤霓。", "xing gong bei yue liu xi han lu dui tang ni" ],
    [ "桃林牛已放，虞坂马长嘶。", "tao lin niu yi fang yu ban fa chang si" ],
    [ "叔侄去官闻广受，弟兄让国有夷齐。", "shu zhi qu guan wen guang shou di xiong rang guo you yi qi" ],
    [ "三月春浓，芍药丛中蝴蝶舞；", "san yue chun nong shao yao cong zhong hu die wu" ],
    [ "五更天晓，海棠枝上子规啼。", "wu geng tian xiao hai tang zhi shang zi gui ti" ],
    [ "云对雨，水对泥，白璧对玄圭。", "yun dui yu shui dui ni bai bi dui xuan gui" ],
    [ "献瓜对投李，禁鼓对征鼙。", "xian gua dui tou li jin gu dui zheng pi" ],
    [ "徐稚榻，鲁班梯，凤翥对鸾栖，", "xu zhi ta lu ban ti feng zhu dui luan qi" ],
    [ "有官清似水，无客醉如泥。", "you guan qing si shui wu ke zui ru ni" ],
    [ "截发惟闻陶侃母，断机只有乐羊妻。", "jie fa wei wen tao kan mu duan ji zhi you yue yang qi" ],
    [ "秋望佳人，目送楼头千里雁；", "qiu wang jia ren mu song lou tou qian li yan" ],
    [ "早行远客，梦惊枕上五更鸡。", "zao xing yuan ke meng jing zhen shang wu geng ji" ],
    [ "熊对虎，象对犀，霹雳对虹霓。", "xiong dui hu xiang dui xi pi li dui hong ni" ],
    [ "杜鹃对孔雀，桂岭对梅溪。", "du juan dui kong que gui ling dui mei xi" ],
    [ "萧史凤，宋宗鸡，远近对高低。", "xiao shi feng song zong ji yuan jin dui gao di" ],
    [ "水寒鱼不跃，林茂鸟频栖。", "shui han yu bu yue lin mao niao pin qi" ],
    [ "杨柳和烟彭泽县，桃花流水武陵溪。", "yang liu he yan peng ze xian tao hua liu shui wu ling xi" ],
    [ "公子追欢，闲骤玉骢游绮陌；", "gong zi zhui huan xian zhou yu cong you qi mo" ],
    [ "佳人倦绣，闷欹珊枕掩香闺。", "jia ren juan xiu men qi shan zhen yan xiang gui" ],
  ],
  [
    [ "河对海，汉对淮，赤岸对朱崖。", "he dui hai han dui huai chi an dui zhu ya" ],
    [ "鹭飞对鱼跃，宝钿对金钗。", "lu fei dui yu yue bao dian dui jin chai" ],
    [ "鱼圉圉，鸟喈喈，草履对芒鞋。", "yu yu yu niao jie jie cao lv dui mang xie" ],
    [ "古贤尝笃厚，时辈喜诙谐。", "gu xian chang du hou shi bei xi hui xie" ],
    [ "孟训文公谈性善，颜师孔子问心斋。", "meng xun wen gong tan xing shan yan shi kong zi wen xin zhai" ],
    [ "缓抚琴弦，像流莺而并语；", "huai fu qin xian xiang liu ying er bing yu" ],
    [ "斜排筝柱。类过雁之相挨。", "xie pai zheng zhu lei guo yan zhi xiang ai" ],
    [ "丰对俭，等对差，布袄对荆钗。", "feng dui jian deng dui cha bu ao dui jing chai" ],
    [ "雁行对鱼阵，榆塞对兰崖。", "yan hang dui yu zhen yu sai dui lan ya" ],
    [ "挑荠女，采莲娃，菊径对苔阶。", "tiao ji nv cai lian wa ju jing dui tai jie" ],
    [ "诗成六义备，乐奏八音谐。", "shi cheng liu yi bei yue zou ba yin xie" ],
    [ "造律吏哀秦法酷，知音人说郑声哇。", "zao lv li ai qin fa ku zhi yin ren shuo zheng sheng wa" ],
    [ "天欲飞霜，塞上有鸿行已过；", "tian yu fei shuang sai shang you hong hang yi guo" ],
    [ "云将作雨，庭前多蚁阵先排。", "yun jiang zuo yu ting qian duo yi zhen xian pai" ],
    [ "城对市，巷对街，破屋对空阶。", "cheng dui shi xiang dui jie po wu dui kong jie" ],
    [ "桃枝对桂叶，砌蚓对墙蜗。", "tao zhi dui gui ye qi yin dui qiang wo" ],
    [ "梅可望，橘堪怀，季路对高柴。", "mei ke wang ju kan huai ji lu dui gao chai" ],
    [ "花藏沽酒市，竹映读书斋。", "hua cang gu jiu shi zhu ying du shu zhai" ],
    [ "马首不容孤竹扣，车轮终就洛阳埋。", "ma shou bu rong gu zhu kou che lun zhong jiu luo yang mai" ],
    [ "朝宰锦衣，贵束乌犀之带；", "chao zai jin yi gui shu wu xi zhi dai" ],
    [ "宫人宝髻，宜簪白燕之钗。", "gong ren bao ji yi zan bai yan zhi chai" ],
  ],
  [
    [ "增对损，闭对开，碧草对苍苔。", "zeng dui sun bi dui kai bi cao dui cang tai" ],
    [ "书签对笔架，两曜对三台。", "shu qian dui bi jia liang yao dui san tai" ],
    [ "周召虎，宋桓魋，阆苑对蓬莱。", "zhou shao hu song huan tui lang yuan dui peng lai" ],
    [ "薰风生殿阁，皓月照楼台。", "xun feng sheng dian ge hao yue zhao lou tai" ],
    [ "却马汉文思罢献，吞蝗唐太冀移灾。", "que ma han wen si ba xian tun huang tang tai ji yi zai" ],
    [ "照耀八荒，赫赫丽天秋日；", "zhao yao ba huang he he li tian qiu ri" ],
    [ "震惊百里，轰轰出地春雷。", "zhen jing bai li hong hong chu di chun lei" ],
    [ "沙对水，火对灰，雨雪对风雷。", "sha dui shui huo dui hui yu xue dui feng lei" ],
    [ "书淫对传癖，水浒对岩隈。", "shu yin dui zhuan pi shui hu dui yan wei" ],
    [ "歌旧曲，酿新醅，舞馆对歌台。", "ge jiu qu niang xin pei wu guan dui ge tai" ],
    [ "春棠经雨放，秋菊傲霜开。", "chun tang jing yu fang qiu ju ao shuang kai" ],
    [ "作酒固难忘曲蘖，调羹必要用盐梅。", "zuo jiu gu nan wang qu nie tiao geng bi yao yong yan mei" ],
    [ "月满庾楼，据胡床而可玩；", "yue man yu lou ju hu chuang er ke wan" ],
    [ "花开唐苑，轰羯鼓以奚催。", "hua kai tang yuan hong jie gu yi xi cui" ],
    [ "休对咎，福对灾，象箸对犀杯。", "xiu dui jiu fu dui zai xiang zhu dui xi bei" ],
    [ "宫花对御柳，峻阁对高台。", "gong hua dui yu liu jun ge dui gao tai" ],
    [ "花蓓蕾，草根荄，剔藓对剜苔。", "hua bei lei cao gen gai ti xian dui wan tai" ],
    [ "雨前庭蚁闹，霜后阵鸿哀。", "yu qian ting yi nao shuang hou zhen hong ai" ],
    [ "元亮南窗今日傲，孙弘东阁几时开。", "yuan liang nan chuang jin ri ao sun hong dong ge ji shi kai" ],
    [ "平展青茵，野外茸茸软草；", "ping zhan qing yin ye wai rong rong ruan cao" ],
    [ "高张翠幄，庭前郁郁凉槐。", "gao zhang cui wo ting qian yu yu liang huai" ]
  ],
  [
    [ "邪对正，假对真，獬豸对麒麟。", "xie dui zheng jia dui zhen xie zhi dui qi lin" ],
    [ "韩卢对苏雁，陆橘对庄椿。", "han lu dui su yan lu ju dui zhuang chun" ],
    [ "韩五鬼，李三人，北魏对西秦。", "han wu gui li san ren bei wei dui xi qin" ],
    [ "蝉鸣哀暮夏，莺啭怨残春。", "chan ming ai mu xia ying zhuan yuan can chun" ],
    [ "野烧焰腾红烁烁，溪流波皱碧粼粼。", "ye shao yan teng hong shuo shuo xi liu bo zhou bi lin lin" ],
    [ "行无踪，居无庐，颂成酒德；", "xing wu zong ju wu lu song cheng jiu de" ],
    [ "动有时，藏有节，论著钱神。", "dong you shi cang you jie lun zhu qian shen" ],
    [ "哀对乐，富对贫，好友对嘉宾。", "ai dui le fu dui pin hao you dui jia bin" ],
    [ "弹冠对结绶，白日对青春。", "tan guan dui jie shou bai ri dui qing chun" ],
    [ "金翡翠，玉麒麟，虎爪对龙麟。", "jin fei cui yu qi lin hu zhao dui long lin" ],
    [ "柳塘生细浪，花径起香尘。", "liu tang sheng xi lang hua jing qi xiang chen" ],
    [ "闲爱登山穿谢屐，醉思漉酒脱陶巾。", "xian ai deng shan chuan xie ji zui si lu jiu tuo tao jin" ],
    [ "雪冷霜严，倚槛松筠同傲岁；", "xue leng shuang yan yi jian song yun ton gao sui" ],
    [ "日迟风暖，满园花柳各争春。", "ri chi feng nuan man yuan hua liu ge zheng chun" ],
    [ "香对火，炭对薪，日观对天津。", "xiang dui huo tan dui xin ri guan dui tian jin" ],
    [ "禅心对道眼，野妇对宫嫔。", "chan xin dui dao yan ye fu dui gong pin" ],
    [ "仁无敌，德有邻，万石对千钧。", "ren wu di de you ling wan dan dui qian jun" ],
    [ "滔滔三峡水，冉冉一溪冰。", "tao tao san xia shui ran ran yi xi bing" ],
    [ "充国功名当画阁，子张言行贵书绅。", "chong guo gong ming dang hua ge zi zhang yan xing dui shu shen" ],
    [ "笃志诗书，思入圣贤绝域；", "du zhi shi shu si ru sheng xian jue yu" ],
    [ "忘情官爵，羞沾名利纤尘。", "wang qing guan jue xiu zhan ming lin xian chen" ],
  ],
  [
    [ "家对国，武对文，四辅对三军。", "jia dui guo wu dui wen si fu dui san jun" ],
    [ "九经对三史，菊馥对兰芬。", "jiu jing dui san shi ju fu dui lan fen" ],
    [ "歌北鄙，咏南薰，迩听对遥闻。", "ge bei bi yong nan xun er ting dui yao wen" ],
    [ "召公周太保，李广汉将军。", "shao gong zhou tai bao li guang han jiang jun" ],
    [ "闻化蜀民皆草偃，争权晋土已瓜分。", "wen hua shu min jie cao yan zheng quan jin tu yi gua fen" ],
    [ "巫峡夜深，猿啸苦哀巴地月；", "wu xia ye shen yuan xiao ku ai ba di yue" ],
    [ "衡峰秋早，雁飞高贴楚天云。", "heng feng qiu zao yan fei gao tie chu tian yun" ],
    [ "欹对正，见对闻，偃武对修文。", "qi dui zheng jian dui wen yan wu dui xiu wen" ],
    [ "羊车对鹤驾，朝旭对晚曛。", "yang che dui he jia zhao xu dui wan xun" ],
    [ "花有艳，竹成文，马燧对羊欣。", "hua you yan zhu cheng wen ma sui dui yang xin" ],
    [ "山中梁宰相，树下汉将军。", "shan zhong liang zai xiang shu xia han jiang jun" ],
    [ "施帐解围嘉道韫，当垆沽酒叹文君。", "shi zhang jie wei jia dao yun dang lu gu jiu tan wen jun" ],
    [ "好景有期，北岭几枝梅似雪；", "hao jing you qi bei ling ji zhi mei si xue" ],
    [ "丰年先兆，西郊千顷稼如云。", "feng nian xian zhao xi jiao qian qing jia ru yun" ],
    [ "尧对舜，夏对殷，蔡惠对刘蕡。", "yao dui shun xia dui yin cai hui dui liu fen" ],
    [ "山明对水秀，五典对三坟。", "shan ming dui shui xiu wu dian dui san fen" ],
    [ "唐李杜，晋机云，事父对忠君。", "tang li du jin ji yun shi fu dui zhong jun" ],
    [ "雨晴鸠唤妇，霜冷雁呼群。", "yu qing jiu huan fu shuang leng yan hu qun" ],
    [ "酒量洪深周仆射，诗才俊逸鲍参军。", "jiu liang hong shen zhou pu ye shi cai jun yi bao can jun" ],
    [ "鸟翼长随，凤兮洵众禽长；", "niao yi chang sui feng xi xun zhong qin zhang" ],
    [ "狐威不假，虎也真百兽尊。", "hu wei bu jia hu ye zhen bai shou zun" ],
  ],
  [
    [ "幽对显，寂对喧，柳岸对桃源。", "you dui xian ji dui xuan liu an dui tao yuan" ],
    [ "莺朋对燕友，早暮对寒暄。", "ying peng dui yan you zao mu dui han xuan" ],
    [ "鱼跃沼，鹤乘轩，醉胆对吟魂。", "yu yue zhao he cheng xuan zui dan dui yin hun" ],
    [ "轻尘生范甑，积雪拥袁门。", "qing chen sheng fan zeng ji xue yong yuan men" ],
    [ "缕缕轻烟芳草渡，丝丝微雨杏花村。", "lv lv qing yan fang cao du si si wei yu xing hua cun" ],
    [ "诣阙王通，献太平十二策；", "yi que wang tong xian tai ping shi er ce" ],
    [ "出关老子，著道德五千言。", "chu guan lao zi zhu dao de wu qian yan" ],
    [ "儿对女，子对孙，药圃对花村。", "er dui nv zi dui sun yao pu dui hua cun" ],
    [ "高楼对邃阁，赤豹对玄猿。", "gao lou dui sui ge chi bao dui xuan yuan" ],
    [ "妃子骑，夫人轩，旷野对平原。", "fei zi ji fu ren xuan kuang ye dui ping yuan" ],
    [ "匏巴能鼓瑟，伯氏善吹埙。", "pao ba neng gu se bo shi shan chui xun" ],
    [ "馥馥早梅思驿使，萋萋芳草怨王孙。", "fu fu zao mei si yi shi qi qi fang cao yuan wang sun" ],
    [ "秋夕月明，苏子黄岗游赤壁；", "qiu xi yue ming su zi huang gang you chi bi" ],
    [ "春朝花发，石家金谷启芳园。", "chun zhao hua fa shi jia jin gu qi fang yuan" ],
    [ "歌对舞，德对恩，犬马对鸡豚。", "ge dui wu de dui en quan ma dui ji tun" ],
    [ "龙池对凤沼，雨骤对云屯。", "long chi dui feng zhao yu zhou dui yun zhun" ],
    [ "刘向阁，李膺门，唳鹤对啼猿。", "liu xiang ge li ying men li ye dui ti yuan" ],
    [ "柳摇春白昼，梅弄月黄昏。", "liu yao chun bai zhou mei nong yue huang hun" ],
    [ "岁冷松筠皆有节，春喧桃李本无言。", "sui leng song yun jie you jie chun xuan tao li ben wu yan" ],
    [ "噪晚齐蝉，岁岁秋来泣恨；", "wan zao qi chan sui sui qiu lai qi hen" ],
    [ "啼宵蜀鸟，年年春去伤魂。", "ti xiao shu niao nian nian chun qu shang hun" ],
  ],
  [
    [ "多对少，易对难，虎踞对龙蟠。", "duo dui shao yi dui nan hu ju dui long pan" ],
    [ "龙舟对凤辇，白鹤对青鸾。", "long zhou dui feng nian bai he dui qing luan" ],
    [ "风淅淅，露漙漙，绣毂对雕鞍。", "feng xi xi lu tuan tuan xiu gu dui diao an" ],
    [ "鱼游荷叶沼，鹭立蓼花滩。", "yu you he ye zhao lu li liao hua tan" ],
    [ "有酒阮貂奚用解，无鱼冯铗必须弹。", "you jiu ruan diao xi yong jie wu yu feng jia bi xu tan" ],
    [ "丁固梦松，柯叶忽然生腹上；", "ding gu meng song ke ye hu ran sheng fu shang" ],
    [ "文郎画竹，枝梢倏尔长毫端。", "wen lang hua zhu zhi shao shu er zhang hao duan" ],
    [ "寒对暑，湿对干，鲁隐对齐桓。", "han dui shu shi dui gan lu yin dui qi huan" ],
    [ "寒毡对暖席，夜饮对晨餐。", "han zhan dui nuan xi ye yin dui chen can" ],
    [ "叔子带，仲由冠，郏鄏对邯郸。", "shu zi dai zhong you guan jia ru dui han dan" ],
    [ "嘉禾忧夏旱，衰柳耐秋寒。", "jia he you xia han shuai liu nai qiu han" ],
    [ "杨柳绿遮元亮宅，杏花红映仲尼坛。", "yang liu lv zhe yuan liang zhai xing hua hong ying zhong ni tan" ],
    [ "江水流长，环绕似青罗带；", "jiang shui liu chang huan rao si qing luo dai" ],
    [ "海蟾轮满，澄明如白玉盘。", "hai chan lun man cheng ming ru bai yu pan" ],
    [ "横对竖，窄对宽，黑志对弹丸。", "heng dui shu zhai dui kuan hei zhi dui dan wan" ],
    [ "朱帘对画栋，彩槛对雕栏。", "zhu lian dui hua dong cai jian dui diao lan" ],
    [ "春既老，夜将阑，百辟对千官。", "chun ji lao ye jiang lan bai bi dui qian guan" ],
    [ "怀仁称足足，抱义美般般。", "huai ren cheng zu zu bao yi mei ban ban" ],
    [ "好马君王曾市骨，食猪处士仅思肝。", "hao ma jun wang ceng shi gu shi zhu chu shi jin si gan" ],
    [ "世仰双仙，元礼舟中携郭泰，", "shi yang shuang xian yuan li zhou zhong xie guo tai" ],
    [ "人称连璧，夏侯车上并潘安。", "ren cheng lian bi xia hou che shang bing pan an" ],
  ],
  [
    [ "兴对废，附对攀，露草对霜菅。", "xing dui fei fu dui pan lu cao dui shuang jian" ],
    [ "歌廉对借寇，习孔对希颜。", "ge lian dui jie kou xi kong dui xi yan" ],
    [ "山垒垒，水潺潺，奉璧对探镮。", "shan lei lei shui chan chan feng bi dui tan huan" ],
    [ "礼由公旦作，诗本仲尼删。", "li you gong dan zuo shi ben zhong ni shan" ],
    [ "驴困客方经灞水，鸡鸣人已出函关。", "lv kun ke fang jing ba shui ji ming ren yi chu han guan" ],
    [ "几夜霜飞，已有苍鸿辞北塞；", "ji ye shuang fei yi you cang hong ci bei sai" ],
    [ "数朝雾暗，岂无玄豹隐南山。", "shu zhao wu an qi wu xuan bao yin nan shan" ],
    [ "犹对尚，侈对悭，雾髻对烟鬟。", "you dui shang chi dui qian wu ji dui yan huan" ],
    [ "莺啼对鹊噪，独鹤对双鹇。", "ying ti dui que zao du he dui shuang xian" ],
    [ "黄牛峡，金马山，结草对衔环。", "huang niu xia jin ma shan jie cao dui xian huan" ],
    [ "昆山惟玉集，合浦有珠还。", "kun shan wei yu ji he pu you zhu huan" ],
    [ "阮籍旧能为眼白，老莱新爱着衣斑。", "ruan ji jiu neng wei yan bai lao lai xin ai zhuo yi ban" ],
    [ "栖迟避世人，草衣木食；", "qi chi bi shi ren cao yi mu shi" ],
    [ "窈窕倾城女，云鬓花颜。", "yao tiao qing cheng nv yun bin hua yan" ],
    [ "姚对宋，柳对颜，赏善对惩奸。", "yao dui song liu dui yan shang shan dui cheng jian" ],
    [ "愁中对梦里，巧慧对痴顽。", "chong zhong dui meng li qiao hui dui chi wan" ],
    [ "孔北海，谢东山，使越对征蛮。", "kong bei hai xie dong shan shi yue dui zheng man" ],
    [ "淫声闻濮上，离曲听阳关。", "yin sheng wen pu shang li qu ting yang guan" ],
    [ "骁将袍披仁贵白，小儿衣着老莱斑。", "xiao jiang pao pi ren gui bai xiao er yi zhuo lao lai ban" ],
    [ "茅舍无人，难却尘埃生榻上；", "mao she wu ren nan que chen ai sheng ta shang" ],
    [ "竹亭有客，尚留风月在窗间。", "zhu ting you ke shang liu feng yue zai chuang jian" ],
  ],
  [
    [ "晴对雨，地对天，天地对山川。", "qing dui yu di dui tian tian di dui shan chuan" ],
    [ "山川对草木，赤壁对青田。", "shan chuan dui cao mu chi bi dui qing tian" ],
    [ "郏鄏鼎，武城弦，木笔对苔钱。", "jia ru ding wu cheng xian mu bi dui tai qian" ],
    [ "金城三月柳，玉井九秋莲。", "jin cheng san yue liu yu jing jiu qiu lian" ],
    [ "何处春朝风景好，谁家秋夜月华圆。", "he chu chun zhao feng jing hao shui jia qiu ye yue hua yuan" ],
    [ "珠缀花梢，千点蔷薇香露；", "zhu zhui hua shao qian dian qiang wei xiang lu" ],
    [ "练横树杪，几丝杨柳残烟。", "lian heng shu miao ji si yang liu can yan" ],
    [ "前对后，后对先，众丑对孤妍。", "qian dui hou hou dui xian zhong chou dui gu yan" ],
    [ "莺簧对蝶板，虎穴对龙渊。", "ying huang dui die ban hu xue dui long yuan" ],
    [ "击石磬，观韦编，鼠目对鸢肩。", "ji shi qing guan wei bian shu mu dui yuan jian" ],
    [ "春园花柳地，秋沼芰荷天。", "chun yuan hua liu di qiu zhao ji he tian" ],
    [ "白羽频挥闲客坐，乌纱半坠醉翁眠。", "bai yu pin hui xian ke zuo wu sha ban zhui zui weng mian" ],
    [ "野店几家，羊角风摇沽酒旆；", "ye dian ji jia yang jiao feng yao gu jiu pei" ],
    [ "长川一带，鸭头波泛卖鱼船。", "chang chuan yi dai ya tou bo fan mai yu chuan" ],
    [ "离对坎，震对乾，一日对千年。", "li dui kan zhen dui qian yi ri dui qian nian" ],
    [ "尧天对舜日，蜀水对秦川。", "yao tian dui shun ri shu shui dui qin chuan" ],
    [ "苏武节，郑虔毡，涧壑对林泉。", "su wu jie zheng qian zhan jian he dui lin quan" ],
    [ "挥戈能退日，持管莫窥天。", "hui ge neng tui ri chi guan mo kui tian" ],
    [ "寒食芳辰花烂熳，中秋佳节月婵娟。", "han shi fang chen hua lan man zhong qiu jia jie yue chan juan" ],
    [ "梦里荣华，飘忽枕中之客；", "meng li rong hua piao hu zhen zhong zhi ke" ],
    [ "壶中日月，安闲市上之仙。", "hu zhong ri yue an xian shi shang zhi xian" ],
  ],
  [
    [ "恭对慢，吝对骄，水远对山遥。", "gong dui man lin dui jiao shui yuan dui shan yao" ],
    [ "松轩对竹槛，雪赋对风谣。", "song xuan dui zhu jian xue fu dui feng yao" ],
    [ "乘五马，贯双雕，烛灭对香消。", "cheng wu ma guan shuang diao zhu mie dui xiang xiao" ],
    [ "明蟾常彻夜，骤雨不终朝。", "ming chan chang che ye zhou yu bu zhong zhao" ],
    [ "楼阁天凉风飒飒，关河地隔雨潇潇。", "lou ge tian liang feng sa sa guan he di ge yu xiao xiao" ],
    [ "几点鹭鸶，日暮常飞红蓼岸；", "ji dian lu si ri mu chang fei hong liao an" ],
    [ "一双鸂鶒，春朝频泛绿杨桥。", "yi shuang xi zhi chun zhao pin fan lv yang qiao" ],
    [ "开对落，暗对昭，赵瑟对虞韶。", "kai dui luo an dui zhao zhao se dui yu shao" ],
    [ "轺车对驿骑，锦绣对琼瑶。", "yao che dui yi ji jin xiu dui qiong yao" ],
    [ "羞攘臂，懒折腰，范甑对颜瓢。", "xiu rang bi lan zhe yao fan zeng dui yan piao" ],
    [ "寒天鸳帐酒，夜月凤台箫。", "han tian yuan zhang jiu ye yue feng tai xiao" ],
    [ "舞女腰肢杨柳软，佳人颜貌海棠娇。", "wu nv yao zhi yang liu ruan jia ren yan mao hai tang jiao" ],
    [ "豪客寻春，南陌草青香阵阵；", "hao ke xun chun nan mo cao qing xiang zhen zhen" ],
    [ "闲人避暑，东堂蕉绿影摇摇。", "xian ren bi shu dong tang jiao lv ying yao yao" ],
    [ "班对马，董对晁，夏昼对春宵。", "ban dui ma dong dui chao xia zhou dui chun xiao" ],
    [ "雷声对电影，麦穗对禾苗。", "lei sheng dui dian ying mai sui dui he miao" ],
    [ "八千路，廿四桥，总角对垂髫。", "ba qian lu nian si qiao zong jiao dui chui tiao" ],
    [ "露桃匀嫩脸，风柳舞纤腰。", "lu tao yun nen lian feng liu wu xian yao" ],
    [ "贾谊赋成伤鵩鸟，周公诗就托鸱鸮。", "jia yi fu cheng shang fu niao zhou gong shi jiu tuo chi xiao" ],
    [ "幽寺寻僧，逸兴岂知俄尔尽；", "you si xun seng yi xing qi zhi e er jin" ],
    [ "长亭送客，离魂不觉黯然消。", "chang ting song ke li hun bu jue an ran xiao" ],
  ],
  [
    [ "风对雅，象对爻，巨蟒对长蛟。", "feng dui ya xiang dui yao ju mang dui chang jiao" ],
    [ "天文对地理，蟋蟀对螵蛸。", "tian wen dui di li xi shuai dui piao xiao" ],
    [ "龙夭矫，虎咆哮，北学对东胶。", "long yao jiao hu pao xiao bei xue dui dong jiao" ],
    [ "筑台须垒土，成屋必诛茅。", "zhu tai xu lei tu cheng wu bi zhu mao" ],
    [ "潘岳不忘秋兴赋，边韶常被昼眠嘲。", "pan yue bu wang qiu xing fu bian shao chang bei zhou mian chao" ],
    [ "抚养群黎，已见国家隆治；", "fu yang qun li yi jian guo jia long zhi" ],
    [ "滋生万物，方知天地泰交。", "zi sheng wan wu fang zhi tian di tai jiao" ],
    [ "蛇对虺，蜃对蛟，麟薮对鹊巢。", "she dui hui sheng dui jiao lin sou dui que chao" ],
    [ "风声对月色，麦穗对桑苞。", "feng sheng dui yue se mai sui dui sang bao" ],
    [ "何妥难，子云嘲，楚甸对商郊。", "he tuo nan zi yun chao chu dian dui shang jiao" ],
    [ "五音惟耳听，万虑在心包。", "wu yin wei er ting wan lv zai xin bao" ],
    [ "葛被汤征因仇饷，楚遭齐伐责包茅。", "ge bei tang zheng yin chou xiang chu zao qi fa ze bao mao" ],
    [ "高矣若天，洵是圣人大道；", "gao yi ruo tian xun shi sheng ren da dao" ],
    [ "淡而如水，实为君子神交。", "dan er ru shui shi wei jun zi shen jiao" ],
    [ "牛对马，犬对猫，旨酒对嘉肴。", "niu dui ma quan dui mao zhi jiu dui jia yao" ],
    [ "桃红对柳绿，竹叶对松梢。", "tao hong dui liu lv zhu ye dui song shao" ],
    [ "藜杖叟，布衣樵，北野对东郊。", "li zhang sou bu yi qiao bei ye dui dong jiao" ],
    [ "白驹形皎皎，黄鸟语交交。", "bai ju xing jiao jiao huang niao yu jiao jiao" ],
    [ "花圃春残无客到，柴门夜永有僧敲。", "hua pu chun can wu ke dao chai men ye yong you seng qiao" ],
    [ "墙畔佳人，飘扬竞把秋千舞；", "qiang pan jia ren piao yang jing ba qiu qian wu" ],
    [ "楼前公子，笑语争将蹴踘抛。", "lou qian gong zi xiao yu zheng jiang cu ju pao" ],
  ],
  [
    [ "琴对瑟，剑对刀，地迥对天高。", "qin dui se jian dui dao di jiong dui tian gao" ],
    [ "峨冠对博带，紫绶对绯袍。", "e guan dui bo dai zi shou dui fei pao" ],
    [ "煎异茗，酌香醪，虎兕对猿猱。", "jian yi ming zhuo xiang lao hu si dui yuan nao" ],
    [ "武夫攻骑射，野妇务蚕缫。", "wu fu gong qi she ye fu wu can sao" ],
    [ "秋雨一川淇澳竹，春风两岸武陵桃。", "qiu yu yi chuan qi yu zhu chun feng liang an wu ling tao" ],
    [ "螺髻青浓，楼外晚山千仞；", "luo ji qing nong lou wai wan shan qian ren" ],
    [ "鸭头绿腻，溪中春水半篙。", "ya tou lv ni xi zhong chun shui ban gao" ],
    [ "刑对赏，贬对褒，破斧对征袍。", "xing dui shang bian dui bao po fu dui zheng pao" ],
    [ "梧桐对橘柚，枳棘对蓬蒿。", "wu tong dui ju you zhi ji dui peng hao" ],
    [ "雷焕剑，吕虔刀，橄榄对葡萄。", "lei huan jian lv qian dao gan lan dui pu tao" ],
    [ "一椽书舍小，百尺酒楼高。", "yi chuan shu she xiao bai chi jiu lou gao" ],
    [ "李白能诗时秉笔，刘伶爱酒每哺糟。", "li bai neng shi shi bing bi liu ling ai jiu mei bu zao" ],
    [ "礼别尊卑，拱北众星常灿灿；", "li bie zun bei gong bei zhong xing chang can can" ],
    [ "势分高下，朝东万水自滔滔。", "shi fen gao xia chao dong wan shui zi tao tao" ],
    [ "瓜对果，李对桃，犬子对羊羔。", "gua dui guo li dui tao quan zi dui yang gao" ],
    [ "春分对夏至，谷水对山涛。", "chun fen dui xia zhi gu shui dui shan tao" ],
    [ "双凤翼，九牛毛，主逸对臣劳。", "shuang feng yi jiu niu mao zhu yi dui chen lao" ],
    [ "水流无限阔，山耸有余高。", "shui liu wu xian kuo shan song you yu gao" ],
    [ "雨打村童新牧笠，尘生边将旧征袍。", "yu da cun tong xin mu li chen sheng bian jiang jiu zheng pao" ],
    [ "俊士居官，荣列鹓鸿之序；", "jun shi ju guan rong lie yuan hong zhi xu" ],
    [ "忠臣报国，誓殚犬马之劳。", "zhong chen bao guo shi dan quan ma zhi lao" ],
  ],
  [
    [ "山对水，海对河，雪竹对烟萝。", "shan dui shui hai dui he xue zhu dui yan luo" ],
    [ "新欢对旧恨，痛饮对高歌。", "xin huan dui jiu hen tong yin dui gao ge" ],
    [ "琴再抚，剑重磨，媚柳对枯荷。", "qin zai fu jian chong mo mei liu dui ku he" ],
    [ "荷盘从雨洗，柳线任风搓。", "he pan zong yu xi liu xian ren feng cuo" ],
    [ "饮酒岂知欹醉帽，观棋不觉烂樵柯。", "yin jiu qi zhi qi zui mao guan qi bu jue lan qiao ke" ],
    [ "山寺清幽，直踞千寻云岭；", "shan si qing you zhi ju qian xun yun ling" ],
    [ "江楼宏敞，遥临万顷烟波。", "jiang lou hong chang yao lin wan qing yan bo" ],
    [ "繁对简，少对多，里咏对途歌。", "fan dui jian shao dui duo li yong dui tu ge" ],
    [ "宦情对旅况，银鹿对铜驼。", "huan qing dui lv kuang yin lu dui tong tuo" ],
    [ "刺史鸭，将军鹅，玉律对金科。", "ci shi ya jiang jun e yu lv dui jin ke" ],
    [ "古堤垂亸柳，曲沼长新荷。", "gu di chui duo liu qu zhao zhang xin he" ],
    [ "命驾吕因思叔夜，引车蔺为避廉颇。", "ming jia lv yiin si shu ye yin che lin wei bi lian po" ],
    [ "千尺水帘，今古无人能手卷；", "qian chi shui lian jin gu wu ren neng shou juan" ],
    [ "一轮月镜，乾坤何匠用功磨。", "yi lun yue jing qian kun he jiang yong gong mo" ],
    [ "霜对露，浪对波，径菊对池荷。", "shuang dui lu lang dui bo jing ju dui chi he" ],
    [ "酒阑对歌罢，日暖对风和。", "jiu lan dui ge ba ri nuan dui feng he" ],
    [ "梁父咏，楚狂歌，放鹤对观鹅。", "liang fu yong chu kuang ge fang he dui guan e" ],
    [ "史才推永叔，刀笔仰萧何。", "shi cai tui yong shu dao bi yang xiao he" ],
    [ "种橘犹嫌千树少，寄梅谁信一枝多。", "zhong ju you xian qian shu shao ji mei shui xin yi zhi duo" ],
    [ "林下风生，黄发村童推牧笠；", "lin xia feng sheng huang fa cun tong tui mu li" ],
    [ "江头日出，皓眉溪叟晒渔蓑。", "jiang tou ri chu hao mei xi sou shai yu suo" ],
  ],
  [
    [ "松对柏，缕对麻，蚁阵对蜂衙。", "song dui bai lv dui ma yi zhen dui feng ya" ],
    [ "頳鳞对白鹭，冻雀对昏鸦。", "cheng lin dui bai lu dong que dui hun ya" ],
    [ "白堕酒，碧沉茶，品笛对吹笳。", "bai duo jiu bi chen cha pin di dui chui jia" ],
    [ "秋凉梧堕叶，春暖杏开花。", "qiu liang wu duo ye chun nuan xing kai hua" ],
    [ "雨长苔痕侵壁砌，月移梅影上窗纱。", "yu zhang tai hen qin bi qi yue yi mei ying shang chuang sha" ],
    [ "飒飒秋风，度城头之筚篥；", "sa sa qiu feng du cheng tou zhi bi li" ],
    [ "迟迟晚照，动江上之琵琶。", "chi chi wan zhao dong jiang shang zhi pi pa" ],
    [ "优对劣，凸对凹，翠竹对黄花。", "you dui lie tu dui ao cui zhu dui huang hua" ],
    [ "松杉对杞梓，菽麦对桑麻。", "song shan dui qi zi shu mai dui sang ma" ],
    [ "山不断，水无涯，煮酒对烹茶。", "shan bu duan shui wu ya zhu jiu dui peng cha" ],
    [ "鱼游池面水，鹭立岸头沙。", "yu you chi mian shui lu li an tou sha" ],
    [ "百亩风翻陶令秫，一畦雨熟邵平瓜。", "bai mu feng fan tao ling shu yi qi yu shu shao ping gua" ],
    [ "闲捧竹根，饮李白一壶之酒；", "xian peng zhu gen yin li bai yi hu zhi jiu" ],
    [ "偶擎桐叶，啜卢同七碗之茶。", "ou qing tong ye chuo lu tong qi wan zhi cha" ],
    [ "吴对楚，蜀对巴，落日对流霞。", "wu dui chu shu dui ba luo ri dui liu xia" ],
    [ "酒钱对诗债，柏叶对松花。", "jiu qian dui shi zhai bai ye dui song hua" ],
    [ "驰驿骑，泛仙槎，碧玉对丹砂。", "chi yi ji fan xian cha bi yu dui dan sha" ],
    [ "设桥偏送笋，开道竟还瓜。", "she qiao pian song sun kai dao jing huan gua" ],
    [ "楚国大夫沉汨水，洛阳才子谪长沙。", "chu guo da fu chen bi shui luo yang cai zi zhe chang sha" ],
    [ "书箧琴囊，乃士流活计；", "shu qie qin nang nai shi liu huo ji" ],
    [ "药炉茶鼎，实闲客生涯。", "yao lu cha ding shi xian ke sheng ya" ],
  ],
  [
    [ "高对下，短对长，柳影对花香。", "gao dui xia duan dui chang liu ying dui hua xiang" ],
    [ "词人对赋客，五帝对三王。", "ci ren dui fu ke wu di dui san wang" ],
    [ "深院落，小池塘，晚眺对晨妆。", "shen yuan luo xiao chi tang wan tiao dui chen zhuang" ],
    [ "绛霄唐帝殿，绿野晋公堂。", "jiang xiao tang di dian lv ye jin gong tang" ],
    [ "寒集谢庄衣上雪，秋添潘岳鬓边霜。", "han ji xie zhuang yi shang xue qiu tian pan yue bin bian shuang" ],
    [ "人浴兰汤，事不忘于端午；", "ren yu lan tang shi bu wang yu duan wu" ],
    [ "客斟菊酒，兴常记于重阳。", "ke zhen ju jiu xing chang ji yu chong yang" ],
    [ "尧对舜，禹对汤，晋宋对隋唐。", "yao dui shun yu dui tang jin song dui sui tang" ],
    [ "奇花对异卉，夏日对秋霜。", "qi hua dui yi hui xia ri dui qiu shuang" ],
    [ "八叉手，九回肠，地久对天长。", "ba cha shou jiu hui chang di jiu dui tian chang" ],
    [ "一堤杨柳绿，三径菊花黄。", "yi di yang liu lv san jing ju hua huang" ],
    [ "闻鼓塞兵方战斗，听钟宫女正梳妆。", "wen gu sai bing fang zhan dou ting zhong gong nv zheng shu zhuang" ],
    [ "春饮方归，纱帽半淹邻舍酒；", "chun yin fang gui sha mao ban yan ling she jiu" ],
    [ "早朝初退，衮衣微惹御炉香。", "zao chao chu tui gun yi wei re yu lu xiang" ],
    [ "荀对孟，老对庄，亸柳对垂杨。", "xun dui meng lao dui zhuang duo liu dui chui yang" ],
    [ "仙宫对梵宇，小阁对长廊。", "xian gong dui fan yu xiao ge dui chang lang" ],
    [ "风月窟，水云乡，蟋蟀对螳螂。", "feng yue ku shui yun xiang xi shuai dui tang lang" ],
    [ "暖烟香霭霭，寒烛影煌煌。", "nuan yan xiang ai ai han zhu ying huang huang" ],
    [ "伍子欲酬渔父剑，韩生尝窃贾公香。", "wu zi yu chou yu fu jian han sheng chang qie jia gong xiang" ],
    [ "三月韶光，常忆花明柳媚；", "san yue shao guang chang yi hua ming liu mei" ],
    [ "一年好景，难忘橘绿橙黄。", "yi nian hao jing nan wang ju lv cheng huang" ],
  ],
  [
    [ "深对浅，重对轻，有影对无声。", "shen dui qian zhong dui qing you ying dui wu sheng" ],
    [ "蜂腰对蝶翅，宿醉对馀酲。", "feng yao dui die chi su zui dui yu cheng" ],
    [ "天北缺，日东生，独卧对同行。", "tian bei que ri dong sheng du wo dui tong xing" ],
    [ "寒冰三尺厚，秋月十分明。", "han bing san chi hou qiu yue shi fen ming" ],
    [ "万卷书容闲客览，一尊酒待故人倾。", "wan juan shu rong xian ke lan yi zun jiu dai gu ren qing" ],
    [ "心侈唐玄，厌看霓裳之曲；", "xin chi tang xuan yan kan ni chang zhi qu" ],
    [ "意骄陈主，饱闻玉树之赓。", "yi jiao chen zhu bao wen yu shu zhi geng" ],
    [ "虚对实，送对迎，后甲对先庚。", "xu dui shi song dui ying hou jia dui xian geng" ],
    [ "鼓琴对舍瑟，搏虎对骑鲸。", "gu qin dui she se bo hu dui qi jing" ],
    [ "金匼匝，玉瑽琤，玉宇对金茎。", "jin ke za yu cong cheng yu yu dui jin jing" ],
    [ "花间双粉蝶，柳内几黄莺。", "hua jian shuang fen die liu nei ji huang ying" ],
    [ "贫里每甘藜藿味，醉中厌听管弦声。", "pin li mei gan li huo wei zui zhong yan ting guan xian sheng" ],
    [ "肠断秋闺，凉吹已侵重被冷；", "chang duan qiu gui liang chui yi qin chong bei leng" ],
    [ "梦惊晓枕，残蟾犹照半窗明。", "meng jing xiao zhen can chan you zhao ban chuang ming" ],
    [ "渔对猎，钓对耕，玉振对金声。", "yu dui lie diao dui geng yu zhen dui jin sheng" ],
    [ "雉城对雁塞，柳袅对葵倾。", "zhi cheng dui yan sai liu niao dui kui qing" ],
    [ "吹玉笛，弄银笙，阮杖对桓筝。", "chui yu di nong yin sheng ruan zhang dui huan zheng" ],
    [ "墨呼松处士，纸号楮先生。", "mo hu song chu shi zhi hao chu xian sheng" ],
    [ "露浥好花潘岳县，风搓细柳亚夫营。", "lu yi hao hua pan yue xian feng cuo xi liu ya fu ying" ],
    [ "抚动琴弦，遽觉座中风雨至；", "fu dong qin xian ju jue zuo zhong feng yu zhi" ],
    [ "哦成诗句，应知窗外鬼神惊。", "e cheng shi ju ying zhi chuang wai gui shen jing" ],
  ],
  [
    [ "红对紫，白对青，渔火对禅灯。", "hong dui zi bai dui qing yu huo dui chan deng" ],
    [ "唐诗对汉史，释典对仙经。", "tang shi dui han shi shi dian dui xian jing" ],
    [ "龟曳尾，鹤梳翎，月榭对风亭。", "gui ye wei he shu ling yue xie dui feng ting" ],
    [ "一轮秋夜月，几点晓天星。", "yi lun qiu ye yue ji dian xiao tian xing" ],
    [ "晋士只知山简醉，楚人谁识屈原醒。", "jin shi zhi zhi shan jian zui chu ren shui zhi qu yuan xing" ],
    [ "绣倦佳人，慵把鸳鸯文作枕；", "xiu juan jia ren yong ba yuan yang wen zuo zhen" ],
    [ "吮毫画者，思将孔雀写为屏。", "shun hao hua zhe si jiang kong que xie wei ping" ],
    [ "行对坐，醉对醒，佩紫对纡青。", "xing dui zuo zui dui xing pei zi dui yu qing" ],
    [ "棋枰对笔架，雨雪对雷霆。", "qi ping dui bi jia yu xue dui lei ting" ],
    [ "狂蛱蝶，小蜻蜓，水岸对沙汀。", "kuang xia die xiao qing ting shui an dui sha ting" ],
    [ "天台孙绰赋，剑阁孟阳铭。", "tian tai sun chuo fu jian ge meng yang ming" ],
    [ "传信子卿千里雁，照书车胤一囊萤。", "chuan xin zi qing qian li yan zhao shu che yin yi nang ying" ],
    [ "冉冉白云，夜半高遮千里月；", "ran ran bai yun ye ban gao zhe qian li yue" ],
    [ "澄澄碧水，宵中寒映一天星。", "cheng cheng bi shui xiao zhong han ying yi tian xing" ],
    [ "书对史，传对经，鹦鹉对鹡鸰。", "shu dui shi zhuan dui jing ying wu dui ji ling" ],
    [ "黄茅对白荻，绿草对青萍。", "huang mao dui bai di lv cao dui qing ping" ],
    [ "风绕铎，雨淋铃，水阁对山亭。", "feng rao duo yu lin ling shui ge dui shan ting" ],
    [ "渚莲千朵白，岸柳两行青。", "zhu lian qian duo bai an liu liang hang qing" ],
    [ "汉代宫中生秀柞，尧时阶畔长祥蓂。", "han dai gong zhong sheng xiu zuo yao shi jie pan zhang xiang ming" ],
    [ "一枰决胜，棋子分黑白；", "yi ping jue sheng qi zi fen hei bai" ],
    [ "半幅通灵，画色间丹青。", "ban fu tong ling hua se jian dan qing" ],
  ],
  [
    [ "新对旧，降对升，白犬对苍鹰。", "xin dui jiu jiang dui sheng bai quan dui cang ying" ],
    [ "葛巾对藜杖，涧水对池冰。", "ge jin dui li zhang jian shui dui chi bing" ],
    [ "张兔网，挂鱼罾，燕雀对鹍鹏。", "zhang tu wang gua yu zeng yan que dui peng kun" ],
    [ "炉中煎药火，窗下读书灯。", "lu zhong jian yao huo chuang xia du shu deng" ],
    [ "织锦逐梭成舞凤，画屏误笔作飞蝇。", "zhi jin zhu suo cheng wu feng hua ping wu bi zuo fei ying" ],
    [ "宴客刘公，座上满斟三雅爵；", "yan ke liu gong zuo shang man zhen san ya jue" ],
    [ "迎仙汉帝，宫中高插九光灯。", "ying xian han di gong zhong gao cha jiu guang deng" ],
    [ "儒对士，佛对僧，面友对心朋。", "ru dui shi fo dui seng mian you dui xin peng" ],
    [ "春残对夏老，夜寝对晨兴。", "chun can dui xia lao ye qin dui chen xing" ],
    [ "千里马，九霄鹏，霞蔚对云蒸。", "qian li ma jiu xiao peng xia wei dui yun zheng" ],
    [ "寒堆阴岭雪，春泮水池冰。", "han dui yin ling xue chun ban shui chi bing" ],
    [ "亚父愤生撞玉斗，周公誓死作金縢。", "ya fu fen sheng zhuang yu dou zhou gong shi zi zuo jin teng" ],
    [ "将军元晖，莫怪人讥为饿虎；", "jiang jun yuan hui mo guai ren ji wei e hu" ],
    [ "侍中卢昶，难逃世号作饥鹰。", "shi zhong lu chang nan tao shi hao zuo ji ying" ],
    [ "规对矩，墨对绳，独步对同登。", "gui dui ju mo dui sheng du bu dui tong deng" ],
    [ "吟哦对讽咏，访友对寻僧。", "yin e dui feng yong fang you dui xun seng" ],
    [ "风绕屋，水襄陵，紫鹄对苍鹰。", "feng rao wu shui xiang ling zi hu dui cang ying" ],
    [ "鸟寒惊夜月，鱼暖上春冰。", "niao han jing ye yue yu nuan shang chun bing" ],
    [ "扬子口中飞白凤，何郎鼻上集青蝇。", "yang zi kou zhong fei bai feng he lang bi shang ji qing ying" ],
    [ "巨鲤跃池，翻几重之密藻；", "ju li yue chi fan ji chong zhi mi zao" ],
    [ "颠猿饮涧，挂百尺之垂藤。", "dian yuan yin jian gua bai chi zhi chui teng" ],
  ],
  [
    [ "荣对辱，喜对忧，夜宴对春游。", "rong dui ru xi dui you ye yan dui chun you" ],
    [ "燕关对楚水，蜀犬对吴牛。", "yan guan dui chu shui shu quan dui wu niu" ],
    [ "茶敌睡，酒消愁，青眼对白头。", "cha di shui jiu xiao chou qing yan dui bai tou" ],
    [ "马迁修史记，孔子作春秋。", "ma qian xiu shi ji kong zi zuo chun qiu" ],
    [ "适兴子猷常泛棹，思归王粲强登楼。", "shi xing zi qiu chang fan zhao si gui wang can qiang deng lou" ],
    [ "窗下佳人，妆罢重将金插鬓；", "chuang xia jia ren zhuang ba chong jiang jin cha bin" ],
    [ "筵前舞妓，曲终还要锦缠头。", "yan qian wu ji qu zhong huan yao jin chan tou" ],
    [ "唇对齿，角对头，策马对骑牛。", "chun dui chi jiao dui tou ce ma dui qi niu" ],
    [ "毫尖对笔底，绮阁对雕镂。", "hao jian dui bi di qi ge dui diao lou" ],
    [ "杨柳岸，荻芦洲，语燕对啼鸠。", "yang liu an di lu zhou yu yan dui ti jiu" ],
    [ "客乘金络马，人泛木兰舟。", "ke cheng jin luo ma ren fan mu lan zhou" ],
    [ "绿野耕夫春举耜，碧池渔父晚垂钩。", "lv ye geng fu chun ju si bi chi yu fu wan chui gou" ],
    [ "波浪千层，喜见蛟龙得水；", "bo lang qian ceng xi jian jiao long de shui" ],
    [ "云霄万里，惊看雕鹗横秋。", "yun xiao wan li jing kan diao e heng qiu" ],
    [ "庵对寺，殿对楼，酒艇对渔舟。", "an dui si dian dui lou jiu ting dui yu zhou" ],
    [ "金龙对彩凤，豮豕对童牛。", "jin long dui cai feng fen shi dui tong niu" ],
    [ "王郎帽，苏子裘，四季对三秋。", "wang lang mao su zi qiu si ji dui san qiu" ],
    [ "峰峦扶地秀，江汉接天流。", "feng luan fu di xiu jiang han jie tian liu" ],
    [ "一湾绿水渔村小，万里青山佛寺幽。", "yi wan lv hui yu cun xiao wan li qing shan fo si you" ],
    [ "龙马呈河，羲皇阐微而画卦；", "long ma cheng he xi huang chan wei er hua gua" ],
    [ "神龟出洛，禹王取法以陈畴。", "shen gui chu luo yu wang qu fa yi chen chou" ],
  ],
  [
    [ "眉对目，口对心，锦瑟对瑶琴。", "mei dui mu kou dui xin jin se dui yao qin" ],
    [ "晓耕对寒钓，晚笛对秋砧。", "xiao geng dui han diao wan di dui qiu zhan" ],
    [ "松郁郁，竹森森，闵损对曾参。", "song yu yu zhu sen sen min sun dui zeng shen" ],
    [ "秦王亲击缶，虞帝自挥琴。", "qin wang qin ji fou yu di zi hui qin" ],
    [ "三献卞和尝泣玉，四知杨震固辞金。", "san xian bian he chang qi yu si zhi yang zhen gu ci jin" ],
    [ "寂寂秋朝，庭叶因霜摧嫩色；", "ji ji qiu zhao ting ye yin shuang cui nen se" ],
    [ "沉沉春夜，砌花随月转清阴。", "chen chen chun ye qi hua sui yue zhuan qing yin" ],
    [ "前对后，古对今，野兽对山禽。", "qian dui hou gu dui jin ye shou dui shan qin" ],
    [ "犍牛对牝马，水浅对山深。", "jian niu dui pi ma shui qian dui shan shen" ],
    [ "曾点瑟，戴逵琴，璞玉对浑金。", "zeng dian se dai kui qin pu yu dui hun jin" ],
    [ "艳红花弄色，浓绿柳敷阴。", "yan hong hua nong se nong lv liu fu yin" ],
    [ "不雨汤王方剪爪，有风楚子正披襟。", "bu yu tang wang fang jian zhao you feng chu zi zheng pi jin" ],
    [ "书生惜壮岁韶华，寸阴尺璧；", "shu sheng xi zhuang sui shao hua cun yin chi bi" ],
    [ "游子爱良宵光景，一刻千金。", "you zi ai liang xiao guang jing yi ke qian jin" ],
    [ "丝对竹，剑对琴，素志对丹心。", "si dui zhu jian dui qin su zhi dui dan xin" ],
    [ "千愁对一醉，虎啸对龙吟。", "qian chou dui yi zui hu xiao dui long yin" ],
    [ "子罕玉，不疑金，往古对来今。", "zi han yu bu yi jin wang gu dui lai jin" ],
    [ "天寒邹吹律，岁旱傅为霖。", "tian han zou chui lv sui han fu wei lin" ],
    [ "渠说子规为帝魄，侬知孔雀是家禽。", "qu shuo zi gui wei di po nong zhi kong que shi jia qin" ],
    [ "屈子沉江，处处舟中争系粽；", "qu zi chen jiang chu chu zhou zhong zheng ji zong" ],
    [ "牛郎渡渚，家家台上竞穿针。", "niu lang du zhu jia jia tai shang jing chuan zhen" ],
  ],
  [
    [ "千对百，两对三，地北对天南。", "qian dui bai liang dui san di bei dui tian nan" ],
    [ "佛堂对仙洞，道院对禅庵。", "fo tang dui xian dong dao yuan dui chan an" ],
    [ "山泼黛，水挼蓝，雪岭对云潭。", "shan po dai shui ruo lan xue ling dui yun tan" ],
    [ "凤飞方翙翙，虎视已眈眈。", "feng fei fang hui hui hu shi yi dan dan" ],
    [ "窗下书生时讽咏，筵前酒客日耽酣。", "chuang xia shu sheng shi feng yong yan qian jiu ke ri dan han" ],
    [ "白草满郊，秋日牧征人之马；", "bai cao man jiao qiu ri mu zheng ren zhi ma" ],
    [ "绿桑盈亩，春时供农妇之蚕。", "lv sang ying mu chun shi gong nong fu zhi can" ],
    [ "将对欲，可对堪，德被对恩覃。", "jiang dui yu ke dui kan de bei dui en tan" ],
    [ "权衡对尺度，雪寺对云庵。", "quan heng dui chi du xue si dui yun an" ],
    [ "安邑枣，洞庭柑，不愧对无惭。", "an yi zao dong ting gan bu kui dui wu can" ],
    [ "魏征能直谏，王衍善清谈。", "wei zheng neng zhi jian wang yan shan qing tan" ],
    [ "紫梨摘去从山北，丹荔传来自海南。", "zi li zhai qu cong shan bei dan li chuan lai zi hai nan" ],
    [ "攘鸡非君子所为，但当月一；", "rang ji fei jun zi suo wei dan dang yue yi" ],
    [ "养狙是山公之智，止用朝三。", "yang ju shi shan gong zhi zhi zhi yong zhao san" ],
    [ "中对外，北对南，贝母对宜男。", "zhong dui wai bei dui nan bei mu dui yi nan" ],
    [ "移山对浚井，谏苦对言甘。", "yi shan dui jun jing jian ku dui yan gan" ],
    [ "千取百，二为三，魏尚对周堪。", "qian qu bai er wei san wei shang dui zhou kan" ],
    [ "海门翻夕浪，山市拥晴岚。", "hai men fan xi lang shan shi yong qing lan" ],
    [ "新缔直投公子纻，旧交犹脱馆人骖。", "xin di zhi tou gong zi zhu jiu jiao you tuo guan ren can" ],
    [ "文达淹通，已咏冰兮寒过水；", "wen 达 yan tong yi yong bing xi han guo shui" ],
    [ "永和博雅，可知青者胜于蓝。", "yong he bo ya ke zhi qing zhe sheng yu lan" ],
  ],
  [
    [ "悲对乐，爱对嫌，玉兔对银蟾。", "bei dui le ai dui xian yu tu dui yin chan" ],
    [ "醉侯对诗史，眼底对眉尖。", "zui hou dui shi shi yan di dui bei jian" ],
    [ "风飁飁，雨绵绵，李苦对瓜甜。", "feng xi xi yu mian mian li ku dui gua tian" ],
    [ "画堂施锦帐，酒市舞青帘。", "hua tang shi jin zhang jiu shi wu qing lian" ],
    [ "横槊赋诗传孟德，引壶酌酒尚陶潜。", "heng shuo fu shi chuan meng de yin hu zhuo jiu shang tao qian" ],
    [ "两曜迭明，日东生而月西出；", "liang yao die ming ri dong sheng er yue xi chu" ],
    [ "五行式序，水下润而火上炎。", "wu xing shi xu shui xia run er huo shang yan" ],
    [ "如对似，减对添，绣幕对朱帘。", "ru dui si jian dui tian xiu mu dui zhu lian" ],
    [ "探珠对献玉，鹭立对鱼潜。", "tan zhu dui xian yu lu li dui yu qian" ],
    [ "玉屑饭，水晶盐，手剑对腰镰。", "yu xie fan shui jing yan shou jian dui yao lian" ],
    [ "燕巢依邃阁，蛛网挂虚檐。", "yan chao yi sui ge zhu wang gua xu yan" ],
    [ "夺槊至三唐敬德，弈棋第一晋王恬。", "duo shuo zhi san tang jing de yi qi di yi jin wang tian" ],
    [ "南浦客归，湛湛春波千顷净；", "nan pu ke gui zhan zhan chun go qian qing jing" ],
    [ "西楼人悄，弯弯夜月一钩纤。", "xi lou ren qiao wan wan ye yue yi gou xian" ],
    [ "逢对遇，仰对瞻，市井对闾阎。", "feng dui yu yang dui zhan shi jing dui lv yan" ],
    [ "投簪对结绶，握发对掀髯。", "tou zan dui jie shou wo fa dui xian ran" ],
    [ "张绣幕，卷珠帘，石碏对江淹。", "zhang xiu mu juan zhu lian shi que dui jiang yan" ],
    [ "宵征方肃肃，夜饮已厌厌。", "xiao zheng fang su su ye yin yi yan yan" ],
    [ "心褊小人长戚戚，礼多君子屡谦谦。", "xin bian xiao ren chang qi qi li duo jun zi lv qian qian" ],
    [ "美刺殊文，备三百五篇诗咏；", "mei ci shu wen bei san bai wu pian shi yong" ],
    [ "吉凶异画，变六十四卦爻占。", "ji xiong yi hua bian liu shi si gua yao zhan" ],
  ],
  [
    [ "清对浊，苦对咸，一启对三缄。", "qing dui zhuo ku dui xian yi qi dui san jian" ],
    [ "烟蓑对雨笠，月榜对风帆。", "yan suo dui yu li yue bang dui feng fan" ],
    [ "莺睍睆，燕呢喃，柳杞对松杉。", "ying xian wan yan ni nan liu qi dui song shan" ],
    [ "情深悲素扇，泪痛湿青衫。", "qing shen bei su shan lei tong shi qing shan" ],
    [ "汉室既能分四姓，周朝何用叛三监。", "han shi ji neng fen si xing zhou chao he yong pan san jian" ],
    [ "破的而探牛心，豪矜王济；", "po di er tan niu xin hao jin wang ji" ],
    [ "竖竿以挂犊鼻，贫笑阮咸。", "shu gan yi gua du bi pin xiao ruan xian" ],
    [ "能对否，圣对贤，卫瓘对浑瑊。", "neng dui fou sheng dui xian wei guan dui hun jian" ],
    [ "雀罗对鱼网，翠巘对苍岩。", "que luo dui yu wang cui yan dui cang yan" ],
    [ "红罗帐，白布衫，笔格对书函。", "hong luo zhang bai bu shan bi ge dui shu han" ],
    [ "蕊香蜂竞采，泥软燕争衔。", "rui xiang feng jing cai ni ruan yan zheng xian" ],
    [ "凶孽誓清闻祖逖，王家能义有巫咸。", "xiong nie shi qing wen zu ti wang jia neng yi you wu xian" ],
    [ "溪叟新居，渔舍清幽临水岸；", "xi sou xin ju yu she qing you lin shui an" ],
    [ "山僧久隐，梵宫寂寞倚云岩。", "shan seng jiu yin fan gong ji mo yi yun yan" ],
    [ "冠对带，帽对衫，议鲠对言谗。", "guan dui dai mao dui shan yi geng dui yan chan" ],
    [ "行舟对御马，俗弊对民岩。", "xing zhou dui yu ma su bi dui min yan" ],
    [ "鼠且硕，兔多毚，史册对书缄。", "shu qie shuo tu duo can shi ce dui shu jian" ],
    [ "塞城闻奏角，江浦认归帆。", "sai cheng wen zou jiao jiang pu ren gui fan" ],
    [ "河水一源形弥弥，泰山万仞势岩岩。", "he shui yi yuan xing mi mi tai shan wan ren shi yan yan" ],
    [ "郑为武公，赋缁衣而美德；", "zheng wei wu gong fu zi yi er mei de" ],
    [ "周因巷伯，歌贝锦以伤谗。", "zhou yin xiang bo ge bei jin yi shang chan" ],
  ]
]

const TITLES = [
  "春晓\n唐 孟浩然",
  "元日\n宋 王安石",
  "声律启蒙 卷上 一东\n清 车万育",
  "声律启蒙 卷上 二冬\n清 车万育",
  "声律启蒙 卷上 三江\n清 车万育",
  "声律启蒙 卷上 四支\n清 车万育",
  "声律启蒙 卷上 五微\n清 车万育",
  "声律启蒙 卷上 六鱼\n清 车万育",
  "声律启蒙 卷上 七虞\n清 车万育",
  "声律启蒙 卷上 八齐\n清 车万育",
  "声律启蒙 卷上 九佳\n清 车万育",
  "声律启蒙 卷上 十灰\n清 车万育",
  "声律启蒙 卷上 十一真\n清 车万育",
  "声律启蒙 卷上 十二文\n清 车万育",
  "声律启蒙 卷上 十三元\n清 车万育",
  "声律启蒙 卷上 十四寒\n清 车万育",
  "声律启蒙 卷上 十五删\n清 车万育",
  "声律启蒙 卷下 一先\n清 车万育",
  "声律启蒙 卷下 二萧\n清 车万育",
  "声律启蒙 卷下 三肴\n清 车万育",
  "声律启蒙 卷下 四豪\n清 车万育",
  "声律启蒙 卷下 五歌\n清 车万育",
  "声律启蒙 卷下 六麻\n清 车万育",
  "声律启蒙 卷下 七阳\n清 车万育",
  "声律启蒙 卷下 八庚\n清 车万育",
  "声律启蒙 卷下 九青\n清 车万育",
  "声律启蒙 卷下 十蒸\n清 车万育",
  "声律启蒙 卷下 十一尤\n清 车万育",
  "声律启蒙 卷下 十二侵\n清 车万育",
  "声律启蒙 卷下 十三覃\n清 车万育",
  "声律启蒙 卷下 十四盐\n清 车万育",
  "声律启蒙 卷下 十五咸\n清 车万育",
]

const FONT_SIZES = [
  36, 36,
  24,24,24,24,24, 24,24,24,24,24, 24,24,24,24,24,
  24,24,24,24,24, 24,24,24,24,24, 24,24,24,24,24,
]